baseURL = "https://elisa-adam.com/"
# baseURL = "http://localhost:1313/"
languageCode = "de-de"
title = "elisa-adam"
disablePathToLower = true

## Needed for css.TailwindCSS
[[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

[markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup]
    [markup.highlight]
        style = 'github'

[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'about-me'
    pageRef = '/about-me'
    weight = 20
  [[menus.main]]
    name = 'workshops'
    pageRef = '/workshops'
    weight = 30
  [[menus.main]]
    name = 'events'
    pageRef = '/events'
    weight = 40
  [[menus.main]]
    name = 'impressum'
    pageRef = '/impressum'
    weight = 50
